{
  "openapi": "3.0.1",
  "info": {
    "title": "Document Compliance Gateway API Documentation",
    "description": "Gateway to allow tax validators to get and update digital tax documents",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://us2.api.concursolutions.com/document-compliance-gateway",
      "description": "US2 Production Environment Concur API EndPoint"
    },
    {
      "url": "https://eu2.api.concursolutions.com/document-compliance-gateway",
      "description": "EU2 Production Environment Concur API EndPoint"
    }
  ],
  "security": [
    {
      "JWT-Token": []
    }
  ],
  "paths": {
    "/v4/tax-documents/{id}": {
      "get": {
        "tags": [
          "Digital Tax Document APIs"
        ],
        "summary": "Get a single digital tax document",
        "description": "Gets the specified digital tax document by documentId.",
        "operationId": "fetchDocument",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Unique identifier for digital tax document",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "concur-correlationid",
            "in": "header",
            "description": "The unique identifier can be used during troubleshooting as it identifies the API call in the log files.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Document Retrieved",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Invalid Document id"
                }
              }
            }
          },
          "401": {
            "description": "Invalid or nonexistent authorization HTTP header",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Authorization Required"
                }
              }
            }
          },
          "403": {
            "description": "Permission Denied",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Access is Forbidden"
                }
              }
            }
          },
          "404": {
            "description": "Unable to find the requested resource",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Page Not Found",
                  "DebugInfo": {
                    "timestamp": "2023-02-14T10:09:44.200+00:00",
                    "path": "/document-compliance-gateway/v4/tax-documents/da665b52-ce6f-4614-82b0-0d15452f8edd"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Internal Server Error",
                  "DebugInfo": {
                    "timestamp": "2023-02-14T10:09:44.200+00:00"
                  }
                }
              }
            }
          },
          "503": {
            "description": "The service is currently unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Service Unavailable"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Digital Tax Document APIs"
        ],
        "summary": "Validate and upload digital tax document",
        "description": "API for uploading digital tax document and upload displayed version of document",
        "operationId": "uploadDocument",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Unique identifier for digital tax document",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "concur-correlationid",
            "in": "header",
            "description": "The unique identifier can be used during troubleshooting as it identifies the API call in the log files.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "digitalTaxDocument"
                ],
                "type": "object",
                "properties": {
                  "digitalTaxDocument": {
                    "$ref": "#/components/schemas/DigitalTaxDocument"
                  },
                  "displayedVersion": {
                    "type": "string",
                    "description": "PDF Displayed version",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Tax document uploaded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DocumentValidationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Invalid tax attributes",
                  "DebugInfo": {
                    "Errors": {
                      "documentData.paymentType": "Invalid PaymentType value"
                    },
                    "Total Error": 1
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid or nonexistent authorization HTTP header",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Authorization Required"
                }
              }
            }
          },
          "403": {
            "description": "Permission Denied",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Access is Forbidden"
                }
              }
            }
          },
          "404": {
            "description": "Unable to find the requested resource",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Page Not Found",
                  "DebugInfo": {
                    "timestamp": "2023-02-14T10:09:44.200+00:00",
                    "path": "/document-compliance-gateway/v4/tax-documents/da665b52-ce6f-4614-82b0-0d15452f8edd"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Internal Server Error",
                  "DebugInfo": {
                    "timestamp": "2023-02-14T10:09:44.200+00:00"
                  }
                }
              }
            }
          },
          "503": {
            "description": "The service is currently unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "Description": "Service Unavailable"
                }
              }
            }
          }
        }
      }
    },
    "/v4/peppol/invoice": {
      "post": {
        "tags": [
          "Peppol Invoice Document APIs"
        ],
        "summary": "Send Peppol Invoice Document",
        "description": "DRC calls this API to send Peppol invoice to Concur",
        "operationId": "receiveInvoice",
        "parameters": [
          {
            "name": "concur-correlationid",
            "in": "header",
            "description": "Concur Correlation Id",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "concur-route",
            "in": "header",
            "description": "Concur Route Header",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DrcInvoiceRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Invoice validated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          },
          "400": {
            "description": "Mandatory fields missing in invoice JSON",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "403": {
            "description": "Access is forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          },
          "404": {
            "description": "Unable to find the Participant",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          },
          "503": {
            "description": "Invoice Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrcInvoiceResponse"
                }
              }
            }
          }
        }
      }
    },
    "/v4/health": {
      "get": {
        "tags": [
          "DCG health check APIs"
        ],
        "summary": "Check DCG health status",
        "description": "DRC calls this API to check for health status",
        "operationId": "healthCheck",
        "parameters": [
          {
            "name": "concur-correlationid",
            "in": "header",
            "description": "Concur Correlation Id",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "concur-route",
            "in": "header",
            "description": "Concur Route Header",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Service is UP",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service is DOWN",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Buyer": {
        "required": [
          "TaxNumber"
        ],
        "type": "object",
        "properties": {
          "TaxNumber": {
            "type": "string",
            "description": "Buyer Tax Number"
          },
          "Name": {
            "type": "string",
            "description": "Buyer Name"
          },
          "PostalCode": {
            "type": "string",
            "description": "Postal code of tax domicile of recipient"
          }
        },
        "description": "Details of the buyer"
      },
      "DigitalTaxDocument": {
        "required": [
          "Status"
        ],
        "type": "object",
        "properties": {
          "Status": {
            "type": "string",
            "description": "Status of the CFDI document",
            "enum": [
              "processed",
              "failed"
            ]
          },
          "DocumentData": {
            "$ref": "#/components/schemas/DocumentData"
          },
          "Description": {
            "type": "string",
            "description": "Comment/description provided by partner"
          },
          "Code": {
            "type": "string",
            "description": "response code provided by partner"
          }
        },
        "description": "Digital Tax Document"
      },
      "DocumentData": {
        "required": [
          "Currency",
          "ExchangeRate",
          "GrossAmount",
          "IssueDateTime",
          "NetAmount",
          "Number",
          "PaymentMethod",
          "UUID",
          "Vendor"
        ],
        "type": "object",
        "properties": {
          "FormatVersion": {
            "type": "string",
            "description": "Version of the CFDI document",
            "enum": [
              "3.3",
              "4.0"
            ]
          },
          "Code": {
            "type": "string",
            "description": "Prefix of receipt (an alphanumeric field that can refer to a physical place (POS, branch, factory, warehouse, office, etc.) or any other criteria (like business, line of product, etc.)"
          },
          "Number": {
            "type": "string",
            "description": "Number of the receipt"
          },
          "IssueDateTime": {
            "type": "string",
            "description": "Date and time when the document was created in the local timezone where it was issued"
          },
          "UUID": {
            "type": "string",
            "description": "Document UUID - field present in CFDI"
          },
          "PaymentType": {
            "type": "string",
            "description": "Means of payment",
            "enum": [
              "Cash",
              "Credit Card",
              "Digital Wallet"
            ]
          },
          "GrossAmount": {
            "type": "number",
            "description": "Sum of amounts before discounts and taxes"
          },
          "Discount": {
            "type": "number",
            "description": "Total amount of applicable discounts before taxes"
          },
          "Currency": {
            "type": "string",
            "description": "Currency used to express amounts (According to the ISO 4217 codes)",
            "enum": [
              "MXN"
            ]
          },
          "ExchangeRate": {
            "type": "number",
            "description": "Exchange Rate according to currency used. Mandatory id currency <> MXN"
          },
          "NetAmount": {
            "type": "number",
            "description": "Sub Total–Discounts+VAT Taxes–Withholding Taxes"
          },
          "PaymentMethod": {
            "type": "string",
            "description": "Specify the code of payment method - PUE - only one payment, PPD - payment done in partial payments,  PIP - Initial payment and partialities"
          },
          "DocumentPostalCode": {
            "type": "string",
            "description": "Postal code of place of issue of receipt"
          },
          "TotalWithholdingTax": {
            "type": "number",
            "description": "Sum of all withhold tax amounts of line items"
          },
          "TotalSalesTax": {
            "type": "number",
            "description": "Sum of all sales tax amounts of line items"
          },
          "VerificationCode": {
            "type": "string",
            "description": "Company's certificate used to generate digital signature"
          },
          "Comments": {
            "type": "string",
            "description": "Comments"
          },
          "Vendor": {
            "$ref": "#/components/schemas/Vendor"
          },
          "Buyer": {
            "$ref": "#/components/schemas/Buyer"
          },
          "LineItems": {
            "type": "array",
            "description": "Line items present in the CFDI",
            "items": {
              "$ref": "#/components/schemas/LineItem"
            }
          }
        },
        "description": "Document data and tax tokens info"
      },
      "LineItem": {
        "required": [
          "Amount",
          "ProductCode"
        ],
        "type": "object",
        "properties": {
          "ProductCode": {
            "type": "string",
            "description": "Key of product or service covered - 10101502 (Dogs), 10101506 (Horses) (Catalogue: c_ClaveProdServ)"
          },
          "Description": {
            "type": "string",
            "description": "Product Description"
          },
          "Amount": {
            "type": "number",
            "description": "Total amount of good or service"
          }
        },
        "description": "Line items present in the CFDI"
      },
      "Vendor": {
        "required": [
          "TaxNumber"
        ],
        "type": "object",
        "properties": {
          "CertificateNumber": {
            "type": "string",
            "description": "Company's certificate used to generate digital signature"
          },
          "TaxNumber": {
            "type": "string",
            "description": "taxpayer ID of the vendor"
          },
          "Name": {
            "type": "string",
            "description": "Name of issuer of receipt"
          },
          "city": {
            "type": "string",
            "description": "City of issuer of receipt"
          },
          "state": {
            "type": "string",
            "description": "State of issuer of receipt"
          },
          "country": {
            "type": "string",
            "description": "Country of issuer of receipt"
          },
          "phone": {
            "type": "string",
            "description": "Phone-Number of issuer of receipt"
          },
          "addressLine": {
            "type": "string",
            "description": "Address of issuer of receipt"
          }
        },
        "description": "Details of the vendor"
      },
      "ErrorResponse": {
        "required": [
          "Description"
        ],
        "type": "object",
        "properties": {
          "Description": {
            "type": "string",
            "description": "Response Description"
          },
          "DebugInfo": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "description": "Additional Debug Information"
            },
            "description": "Additional Debug Information"
          }
        }
      },
      "DocumentValidationResponse": {
        "required": [
          "DocumentId"
        ],
        "type": "object",
        "properties": {
          "DocumentId": {
            "type": "string",
            "description": "The id of document"
          },
          "Description": {
            "type": "string",
            "description": "Description"
          }
        }
      },
      "DcsInvoiceAttachment": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "fileName": {
            "type": "string"
          },
          "contentType": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      },
      "DcsInvoiceDocument": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "contentType": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "attachments": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DcsInvoiceAttachment"
            }
          }
        }
      },
      "DrcInvoiceRequest": {
        "type": "object",
        "properties": {
          "processType": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "action": {
            "type": "string"
          },
          "channel": {
            "type": "string"
          },
          "sender": {
            "type": "string"
          },
          "receiver": {
            "type": "string"
          },
          "document": {
            "$ref": "#/components/schemas/DcsInvoiceDocument"
          }
        }
      },
      "DrcInvoiceResponse": {
        "type": "object",
        "properties": {
          "invoiceNumber": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "participantId": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "JWT-Token": {
        "type": "http",
        "description": "Partner JWT Token",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "x-sap-shortText": "Compliance APIs for Receipt and Invoice"
}
